export enum OpCode {
  MOVE_REQUEST = 1,
  MOVE_BROADCAST = 2,
  PLAYER_JOINED = 3,
  PLAYER_LEFT = 4,
  WORLD_SNAPSHOT = 5,
  MOVE_REJECTED = 6,

  GATHER_REQUEST = 7,
  GATHER_STARTED = 8,
  GATHER_RESULT = 9,
  GATHER_CANCELLED = 10,
  NODE_STATE = 11,
  NODES_SNAPSHOT = 12,

  BUILD_REQUEST = 13,
  BUILD_BROADCAST = 14,
  ISLAND_SNAPSHOT = 15
}
